name: Build and Package WPF App
on: [push]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository code
      uses: actions/checkout@v2

    - name: Copy project as artifact
      run: |
        # Copy the entire project directory to the artifacts folder
        cp -r . ${{ github.workspace }}/artifacts

    - name: Publish artifacts
      uses: actions/upload-artifact@v2
      with:
        name: my-wpf-app-artifacts
        path: ${{ github.workspace }}/artifacts

      
