name: Build and Package WPF App
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository code
      uses: actions/checkout@v2

    - name: Set up .NET Core SDK
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '3.1'

    - name: Restore NuGet packages
      run: dotnet restore

    - name: Build the WPF App
      run: dotnet build -c Release -o ./bin

    - name: Copy artifacts
      run: cp -r ./bin ${{ github.workspace }}/artifacts

    - name: Publish artifacts
      uses: actions/upload-artifact@v2
      with:
        name: my-wpf-app-artifacts
        path: ${{ github.workspace }}/artifacts

      
